// SUNPLUS  S+core IDE generated include file.
#ifndef HYPERSCAN_RESOURCE_H__11942_2995__INCLUDED_
#define HYPERSCAN_RESOURCE_H__11942_2995__INCLUDED_

extern unsigned char* _binary_C__Users_ppcasm_Desktop_HyperScan_SPG29x_SDK_main_examples_hyperscan_cd_usbloadercd_cdusbldr_bin_start;
#define RES_CDUSBLDR_BIN (unsigned char*)&_binary_C__Users_ppcasm_Desktop_HyperScan_SPG29x_SDK_main_examples_hyperscan_cd_usbloadercd_cdusbldr_bin_start
extern unsigned char* _binary_C__Users_ppcasm_Desktop_HyperScan_SPG29x_SDK_main_examples_hyperscan_cd_usbloadercd_cdusbldr_bin_end;
#define RES_CDUSBLDR_BIN_END (unsigned char*)&_binary_C__Users_ppcasm_Desktop_HyperScan_SPG29x_SDK_main_examples_hyperscan_cd_usbloadercd_cdusbldr_bin_end


#endif //HYPERSCAN_RESOURCE_H__11942_2995__INCLUDED_
